config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  post 'login_register', to: 'pages#login_register'

  resources :movies, only: %w[new create]

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user

  validates :movie_url, presence: true, format: /\A(http[s]\:\/\/)?(www\.youtube\.com|youtu\.?be)\/.+$\z/
  validates :user, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :validatable

  has_many :movies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend

  def authenticate_user!
    if user_signed_in?
      super
    else
      redirect_to root_path, alert: 'You need to sign in or sign up before continuing.'
    end
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user!

  def new
    @movie = current_user.movies.new
  end

  def create
    @movie = current_user.movies.new(movie_params)

    if @movie.save
      redirect_to root_path, notice: 'Movie shared succesfully'
    else
      render :new
    end
  end

  private

  def movie_params
    params.require(:movie).permit(:movie_url, :user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :prepare_data, only: :home

  def home
    @user = User.new
    respond_to do |format|
      format.json do
        html = render_to_string(
          partial: 'movies/movie',
          collection: @movies,
          as: :movie,
          layout: false,
          formats: [:html]
        )
        render json: { success: true, html: html, next_page: @pagy.next, last_page: @pagy.page == @pagy.last, movie_ids: @movies.pluck(:id) }
      end
      format.html
    end
  end

  def login_register
    if params[:commit] == 'Login'
      handle_login
    elsif params[:commit] == 'Register'
      handle_register
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

  def handle_login
    @user = User.find_by(email: user_params[:email])

    return redirect_to root_path, alert: 'User not found!' if @user.blank?

    return redirect_to root_path, alert: 'Wrong password!' unless @user.valid_password?(user_params[:password])

    sign_in @user
    redirect_to root_path, notice: 'Logged succesfully'
  end

  def handle_register
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, notice: 'Account registered successfully'
    else
      prepare_data
      render 'home'
    end
  end

  def prepare_data
    @movies = Movie.order(id: :desc)
    @pagy, @movies = pagy(Movie.order(id: :desc), items: 5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def youtube_embed(youtube_url)
    if youtube_url[/youtu\.be\/([^\?]*)/]
      youtube_id = $1
    else
      youtube_url[/^.*((v\/)|(embed\/)|(watch\?))\??v?=?([^\&\?]*).*/]
      youtube_id = $5
    end

    youtube_id
  end
end

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="closeable-alert" class="bg-danger p-0-5-rem rounded text-white">
    <div class="close-icon">
      <svg xmlns="http://www.w3.org/2000/svg" class="h-1 w-1 x-icon" width="20" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" class="x-icon" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
      </svg>
    </div>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_message.html.erb
<% flash.each do |key, value| %>
  <div id="closeable-alert" class="alert p-0-5-rem text-white rounded bg-<%= key %>">
    <div class="close-icon">
      <svg xmlns="http://www.w3.org/2000/svg" class="h-1 w-1 x-icon" width="20" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" class="x-icon" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
      </svg>
    </div>
    <%= value %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header class="main-menu">
  <%= render partial: "layouts/error_messages", locals: { object: @user } if current_user.blank? %>
  <div class="main-menu-container">
    <div class="mx-0-5-rem p-0-5-rem brand-wrapper">
      <svg xmlns="http://www.w3.org/2000/svg" width="70" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
        <path d="M10.707 2.293a1 1 0 00-1.414 0l-7 7a1 1 0 001.414 1.414L4 10.414V17a1 1 0 001 1h2a1 1 0 001-1v-2a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 001 1h2a1 1 0 001-1v-6.586l.293.293a1 1 0 001.414-1.414l-7-7z" />
      </svg>
      <div class="brand">Funny Movies</div>
    </div>

    <% if current_user.present? %>
      <div class="login-register-form">
        <div class="p-0-5-rem mx-0-5-rem"><%= current_user.email %></div>
        <%= link_to "Share a movie", new_movie_path, class: "rounded btn text-white p-0-5-rem mx-0-5-rem" %>
        <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "rounded btn-outline text-orange p-0-5-rem mx-0-5-rem" %>
      </div>

    <% else %>
      <%= form_for(@user, as: :user, url: login_register_path, html: { class: "login-register-form" }) do |f| %>
        <div class="field">
          <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "input rounded p-0-5-rem mx-0-5-rem", placeholder: 'Email...' %>
        </div>

        <div class="field">
          <%= f.password_field :password, autocomplete: "new-password", class: "input rounded p-0-5-rem mx-0-5-rem", placeholder: 'Password ...' %>
        </div>

        <div class="register-action">
          <%= f.submit "Register", class: "rounded btn-outline text-orange p-0-5-rem mx-0-5-rem" %>
        </div>

        <div class="login-action">
          <%= f.submit "Login", class: "rounded btn text-white p-0-5-rem mx-0-5-rem" %>
        </div>

      <% end %>
    <% end %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FunnyMovies</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render partial: "layouts/flash_message" %>
      <%= render partial: "layouts/header" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/movies/_movie.html.erb
<%- movie_url = youtube_embed(movie.movie_url) %>
<div class="movie-item" data-target="movies.movieItem" data-youtube-id="<%= movie_url %>" data-internal-id="<%= movie.id %>">
  <div class="movie-media">
    <iframe src="https://www.youtube.com/embed/<%= movie_url %>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  </div>
  <div class="movie-info">
    <h2 class="text-orange movie-title">Tommy play guitar</h2>
    <p>Share by: <%= movie.user.email %></p>
    <p>Description: </p>
    <p>
      <strong class="movie-description">
        is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
      </strong>
    </p>
  </div>
</div>

app/views/movies/new.html.erb
<div class="movie-form-wrapper">
  <%= form_for(@movie, as: :movie, url: movies_path, html: { class: 'movie-form' }) do |f| %>
    <div class="form-title">Share a Youtube movie</div>

    <div class="field-wrapper text-field">
      <%= f.text_field :movie_url, class: "input rounded p-0-5-rem", placeholder: '' %>
    </div>
    <% if @movie.errors.any? %>
      <div class="error-fields">
        <%= @movie.errors.full_messages_for(:movie_url).join(', ') %>
      </div>
    <% end %>
    <div class="field-wrapper">
      <%= f.submit 'Share', class: "btn text-white p-0-5-rem" %>
    </div>
  <% end %>
</div>

app/views/pages/home.html.erb
<div
  class="home-page-container"
  data-controller="movies"
  data-next-page="<%= @pagy.next %>"
  data-last-page="<%= @pagy.page == @pagy.last %>"
  data-youtube-api-key="<%= ENV['YOUTUBE_API_KEY'] %>"
>
  <% if @movies.present? %>
    <div class="movies" data-target="movies.list">
      <%= render partial: "movies/movie", collection: @movies, as: :movie %>
    </div>
    <% if @pagy.next %>
      <button class="btn text-white rounded p-0-5-rem loadmore-btn" data-target="movies.loadmoreBtn" data-action="movies#loadmore">See more</button>
    <% end %>
  <% else %>
    <h1 class="empty-items-msg">No available movies</h1>
  <% end %>
</div>